name: Cypress Tests
on: push
  # pull_request:
  #   branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install 
        run: npm install
      - name: Start app 
        run: yarn start-devnet
      - name: Cypress run
        run: npm run cy:run
      - name: Uploading artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
            name: cypress-execution-report
            path: cypress/reports/mochawesome.html
            retention-days: 30      
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_USERNAME: cypress-report
            SLACK_TITLE: E2E TESTS
            SLACK_MESSAGE: "Cypress report test"
       